### ISSUE TITLE
PyTorch 2.1 support

### ISSUE THREAD

**Issue by schmidt-ai** [facebookresearch/dinov2#265]
Looks like there are some breaking changes to the FSDP API in PyTorch 2.1.

For example, `dinov2.fsdp.__init__.py::free_if_fsdp` is broken when using torch==2.1: `AttributeError: 'DinoVisionTransformer' object has no attribute '_handles'`

**Comment by qasfb** [comment]
Thanks for reporting ! We are still working on the transition to PT2.1 @patricklabatut

**Comment by dsuess** [comment]
I found the following in pytorch 2.1:

```
def free_if_fsdp(x: FSDP):
    if is_sharded_fsdp(x) and x._has_params:
        handle = x._handle
        _reshard(x, handle, True)
```
